name: Daily Commit

on:
  schedule:
    - cron: '30 8 * * *'  # runs daily at 08:30 UTC

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make a change
        run: |
          echo "Last updated: $(date -u)" > last-updated.txt

      - name: Commit and push
        run: |
          git config user.name "DevSync Bot"
          git config user.email "23f2004940@ds.study.iitm.ac.in"
          git add last-updated.txt
          git commit -m "Daily update"
          git push

      - name: Verification step for 23f2004940@ds.study.iitm.ac.in
        run: echo "Email step check passed"
